apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spedisjon
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
  env:
  - name: KAFKA_CONSUMER_GROUP_ID
    value: spedisjon-v1
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_EXTRA_TOPIC
    value: flex.sykepengesoknad,helsearbeidsgiver.privat-sykepenger-inntektsmelding
  - name: DATABASE_HOST
    value: b27dbvl009.preprod.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: spedisjon
  - name: VAULT_MOUNTPATH
    value: postgresql/preprod-fss/


