apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spedisjon
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 3000m
      memory: 4096Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-prod
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvspedisjon
  env:
  - name: KAFKA_CONSUMER_GROUP_ID
    value: spedisjon-v1
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_EXTRA_TOPIC
    value: flex.sykepengesoknad,helsearbeidsgiver.privat-sykepenger-inntektsmelding
  - name: DATABASE_HOST
    value: a01dbfl039.adeo.no
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: spedisjon
  - name: VAULT_MOUNTPATH
    value: postgresql/prod-fss/
  - name: AKTORREGISTERET_URL
    value: https://app.adeo.no/aktoerregister
